# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2023-04-09 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Active Name',
                'verbose_name_plural': 'Active Names',
            },
        ),
        migrations.CreateModel(
            name='Customer_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('destination_area', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_area', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
            options={
                'verbose_name': 'Customer Rating',
                'verbose_name_plural': 'Customer Ratings',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_number', models.CharField(blank=True, max_length=22, null=True)),
                ('driver_name', models.CharField(max_length=40, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('son_of', models.CharField(max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=22, null=True)),
                ('dl_number', models.CharField(max_length=22)),
                ('dl_expiry', models.DateField(blank=True, null=True)),
                ('driver_image', models.ImageField(default='images/profile.png', upload_to='images/drivers')),
                ('driver_image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/drivers')),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True)),
                ('is_image_verified', models.BooleanField(default=False)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=40, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('son_of', models.CharField(max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=22, null=True)),
                ('owner_image', models.ImageField(default='images/profile.png', upload_to='images/owners')),
                ('owner_image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('dl_number', models.CharField(blank=True, max_length=22, null=True)),
                ('dl_expiry', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True)),
                ('is_image_verified', models.BooleanField(default=False)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Rating_Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
            options={
                'verbose_name': 'Rating Reason',
                'verbose_name_plural': 'Rating Reasons',
            },
        ),
        migrations.CreateModel(
            name='Rating_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
            options={
                'verbose_name': 'Rating Type',
                'verbose_name_plural': 'Rating Types',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_number', models.CharField(default='', max_length=28, unique=True)),
                ('number_plate', models.CharField(max_length=24)),
                ('autostand', models.CharField(blank=True, max_length=80, null=True, verbose_name='Stand')),
                ('union', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance', models.DateField(blank=True, null=True)),
                ('pollution', models.DateField(blank=True, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=40, null=True)),
                ('chasis_number', models.CharField(blank=True, max_length=30, null=True)),
                ('is_owner_driver', models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('DRIVER', 'Driver')], default='OWNER', max_length=6, null=True)),
                ('rc_expiry', models.DateField(blank=True, null=True)),
                ('num_of_complaints', models.BigIntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/vehicles')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=20, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity_of_passengers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('registered', models.BooleanField(default=False)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Source')),
            ],
            options={
                'verbose_name': 'Vehicle_Registration',
                'verbose_name_plural': 'Vehicle_Registration',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=10, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active')),
            ],
            options={
                'verbose_name': 'Vehicle type',
                'verbose_name_plural': 'Vehicle types',
            },
        ),
        migrations.RemoveField(
            model_name='complaint_statement',
            name='taxi',
        ),
        migrations.AddField(
            model_name='city_code',
            name='messaging_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='is_emergency_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='resolved_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint_statement',
            name='destination_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_statement',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Reasons'),
        ),
        migrations.AddField(
            model_name='vehicle_registration',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Vehicle_type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicledetails', to='taxiapp.City_Code'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Owner'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Vehicle_type'),
        ),
        migrations.AddField(
            model_name='rating_reason',
            name='rating_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Rating_Type'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='taxiapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='customer_rating',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Driver'),
        ),
        migrations.AddField(
            model_name='customer_rating',
            name='rating_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Rating_Type'),
        ),
        migrations.AddField(
            model_name='customer_rating',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Active'),
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Vehicle', verbose_name='Vehicle ID'),
        ),
    ]
