# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2023-04-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0002_auto_20230409_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_statement',
            name='number_plate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
