# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0002_auto_20170320_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxi_detail',
            name='web_page_url',
        ),
        migrations.AddField(
            model_name='taxi_detail',
            name='driver_image',
            field=models.ImageField(default='media/default_qr.png', upload_to='media'),
        ),
        migrations.AddField(
            model_name='taxi_detail',
            name='qr_image',
            field=models.ImageField(default='media/default_qr.png', upload_to='media'),
        ),
    ]
