# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0002_auto_20170329_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.City_Code'),
        ),
    ]
