# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0003_auto_20170329_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_code',
            name='complaint_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city_code',
            name='police_no',
            field=models.IntegerField(default=0),
        ),
    ]
