# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2023-04-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0003_complaint_statement_number_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_statement',
            name='latitute',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='longitude',
            field=models.CharField(default='', max_length=200),
        ),
    ]
