# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0004_auto_20170329_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.AddField(
            model_name='myuser',
            name='area',
            field=models.CharField(default='Hyderabad', max_length=200),
            preserve_default=False,
        ),
    ]
