# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2023-04-15 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0004_auto_20230414_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_statement',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
