# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0005_auto_20170330_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_statement',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
