# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0006_auto_20170330_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_statement',
            name='area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint_statement',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.City_Code'),
        ),
        migrations.AlterField(
            model_name='complaint_statement',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Reasons'),
        ),
        migrations.AlterField(
            model_name='complaint_statement',
            name='taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Taxi_Detail'),
        ),
    ]
