# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0007_auto_20170330_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_statement',
            name='complaint_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
