# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0008_auto_20170330_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city_code',
            options={'verbose_name': 'City Code', 'verbose_name_plural': 'City Codes'},
        ),
    ]
