# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0011_auto_20170330_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_statement',
            name='phone_number',
            field=models.CharField(default='None', max_length=13),
            preserve_default=False,
        ),
    ]
