# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0012_complaint_statement_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_code',
            name='sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='city_code',
            name='whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
