# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0013_auto_20170412_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='whatsapp_number',
            field=models.IntegerField(null=True),
        ),
    ]
