# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0014_myuser_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi_detail',
            name='traffic_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
