# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0016_auto_20170413_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_statement',
            name='destination_area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='complaint_statement',
            name='origin_area',
            field=models.CharField(default='', max_length=200),
        ),
    ]
