# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0017_auto_20170418_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_statement',
            name='destination_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_statement',
            name='origin_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
