# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0018_auto_20170420_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_code',
            name='distress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city_code',
            name='distress_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
