# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0019_auto_20170325_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_statement',
            name='complaint',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
