# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0021_auto_20170327_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi_detail',
            old_name='qrcode',
            new_name='qr_code',
        ),
    ]
