# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0025_auto_20170328_1800'),
        ('taxiapp', '0026_auto_20170328_1643'),
    ]

    operations = [
    ]
