# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0027_merge_20170328_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
