# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Details',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('access_level', models.IntegerField()),
            ],
        ),
    ]
