# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Details',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sms_number', models.IntegerField()),
                ('whatsapp_number', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Statements',
            fields=[
                ('complaint_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taxi_Details',
            fields=[
                ('taxi_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('number_plate', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=40)),
                ('web_page_url', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('other_details', models.CharField(blank=True, max_length=200)),
                ('num_of_complaints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Complaint',
            fields=[
                ('complaint_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_locations_x', models.IntegerField()),
                ('user_locations_y', models.IntegerField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Admin_Details')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Complaint_Statements')),
                ('taxi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Taxi_Details')),
            ],
        ),
    ]
