# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0002_admin_details_complaint_statements_taxi_details_user_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_complaint',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='user_complaint',
            name='complaint_id',
        ),
        migrations.RemoveField(
            model_name='user_complaint',
            name='taxi_id',
        ),
        migrations.DeleteModel(
            name='Admin_Details',
        ),
        migrations.DeleteModel(
            name='Complaint_Statements',
        ),
        migrations.DeleteModel(
            name='Taxi_Details',
        ),
        migrations.DeleteModel(
            name='User_Complaint',
        ),
    ]
