# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0004_admin_details_complaint_statements_taxi_details_user_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_details',
            name='password',
            field=models.CharField(default='iiit123', max_length=20),
        ),
    ]
