# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0005_login_details_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
