version: "3"
services:

  taxi-db:
    container_name: taxi-db
    image: postgres:11-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: taxidb
      POSTGRES_USER: valv_admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  taxi-web:
    container_name: taxi-web
    build:
      dockerfile: Dockerfile
    image: taxiapp:latest
    command: >
      bash -c "nginx -g 'daemon on;'
      && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - taxi-db
    ports:
      - 80:80
      - 443:443
    environment:
      POSTGRES_DB: taxidb
      POSTGRES_USER: valv_admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: taxi-db
